//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BEZAI_MOHAMMED_EXAMEN_FINAL_DOTNET_4ISI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Opération
    {
        public int Id { get; set; }
        public string type { get; set; }
        public System.DateTime date { get; set; }
        public string montant { get; set; }
    
        public virtual Compte Compte { get; set; }
    }
}
